### ISSUE TITLE
Should respect rotation settings

### ISSUE THREAD

**Issue by giner** [KeikaiLauncher/KeikaiLauncher#9]
Launcher has it's own rotation settings and doesn't respect the system ones.

**Comment by avuton** [comment]
I feel like I'm not understanding this, but here it goes anyhow. Most launchers (including AOSP) disable rotation by default, as does this launcher. If that setting is toggled, rotation should work just fine.

**Comment by avuton** [comment]
With that said, I don't really mind changing the default, I toggle it anytime I require a new settings file.

**Comment by giner** [comment]
The problem with having different global and launcher rotation settings is that screen flips every time when switching between apps while using smartphone horizontally. To avoid this it is required to change settings in both (launcher and Android global) places every time.

**Comment by avuton** [comment]
Years ago, when I used AOSP's launcher, it had the same behaviour (landscape goes to portrait launcher). Maybe the world has changed and this is not the current behaviour of launchers.

I'd be happy to default to not locking to portrait. The option could, obviously, be removed as well, but I know for a fact that some users find landscape launchers annoying.

Do you think not locking to portrait by default would be suitable to resolve this issue @giner?

**Comment by giner** [comment]
The current behavior of the locking option is forbid/allow rotation. What about forbid/"respect the system settings" instead?

**Comment by avuton** [comment]
Aaah, I see the bug now. Sorry for being so dense, I don't ever lock my orientation, so that, certainly, should be fixed.

The issue:

If orientation is locked by system settings, orientation change shouldn't be allowed. Should be a somewhat easy fix.

**Comment by edio** [comment]
@avuton , sure, feel free to take this :D
BTW, I believe, I sent you an invite to be an owner of the project btw. Let me resend it.

**Comment by avuton** [comment]
Thanks, I'll figure out what's going on. Probably spam filter or something.

**Comment by avuton** [comment]
Fix pending at https://github.com/avuton/KeikaiLauncher/commit/17600440946bcf6165673fdaa0c17e70d3ff09dd. It's going to be a little bit before I push it here mostly due to https://github.com/avuton/KeikaiLauncher/commit/d9661386b8fd209af2ce197286047626d8721dbb which should have been part of the release, otherwise the launcher is fairly jank. I've been running https://github.com/avuton/KeikaiLauncher/commit/d9661386b8fd209af2ce197286047626d8721dbb since it was committed, but I need to review the patch a bit more before it ships. I'd appreciate testing, but I know I have better luck tracking down unicorns than getting people to compile alternate forks.
